/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Appointment.WorkQueue.AppointmentBookingWorkRequest;
import Business.Appointment.WorkQueue.AppointmentWorkRequest;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varad
 */
public class DoctorScheduleAppointmentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorScheduleAppointmentsJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    public DoctorScheduleAppointmentsJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        usernamelbl.setText("Hello "+userAccount.getUsername());
       
        valueLabel.setText(enterprise.getName());
        populateAppointmentTable();
    }

    public void populateAppointmentTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        
        model.setRowCount(0);
        for (AppointmentWorkRequest r : userAccount.getAppointmentWorkQueue().getAppointmentWorkRequestList()){
            String result = ((AppointmentBookingWorkRequest)r).getBookingResult();
            if(result!=null)
            {
            if(r.getSender().equals(userAccount))
            {
            Object[] row = new Object[5];
            row[0] = r;
            row[2] = r.getDate();
            row[3] = r.getTime();
           // row[4] = r.getStatus();
            
            if(result==null)
            {
               row[4] = r.getStatus();
               row[1]="-";
            }
            else
            {
               
                row[4] = result;
                row[1] = r.getReceiver();
            }
              
            model.addRow(row);
            }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        requestTestJButton1 = new javax.swing.JButton();
        usernamelbl = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        requestTestJButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment Number", "Username", "date", "Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 99, 480, 130));

        requestTestJButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        requestTestJButton1.setText("Update Status");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });
        add(requestTestJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 40));

        usernamelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(usernamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 26));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 81, 40));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("EnterPrise :");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("EnterPrise :");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        requestTestJButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        requestTestJButton2.setText("Search");
        requestTestJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton2ActionPerformed(evt);
            }
        });
        add(requestTestJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, 40));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
        AppointmentWorkRequest r=(AppointmentWorkRequest) workRequestJTable1.getValueAt(workRequestJTable1.getSelectedRow(), 0);
        String result = ((AppointmentBookingWorkRequest)r).getBookingResult();
       if(result==null)      
       {
        JOptionPane.showMessageDialog(null, "Appointment is not booked yet");
       }
       else if(result.equals("Checked In"))
       {
        JOptionPane.showMessageDialog(null, "Status is already updated");   
       }
       else
       {
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorAddAppointmentsJPanel", new DoctorUpdateCheckInStatus(userProcessContainer, userAccount, enterprise, organization,r));
        layout.next(userProcessContainer);  
       }
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Please select a record!");
        }
        
    }//GEN-LAST:event_requestTestJButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void requestTestJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton2ActionPerformed
        // TODO add your handling code here:
         String username= jTextField1.getText();
       
        
        
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);
        
        for(AppointmentWorkRequest r: userAccount.getAppointmentWorkQueue().getAppointmentWorkRequestList())
        {
            String result = ((AppointmentBookingWorkRequest)r).getBookingResult();
            if(result!=null)
            {
             if(r.getSender().equals(userAccount))
            {   
            if(r.getReceiver().getUsername().equals(username))
            {
                
                Object[] row = new Object[5];
                row[0] = r;
                row[2] = r.getDate();
                row[3] = r.getTime();
                if(result==null)
                {
               row[4] = r.getStatus();
               row[1]="-";
                 }
                else
                 {
               
                row[4] = result;
                row[1] = r.getReceiver();
                 }
            
            model.addRow(row);
            }
            }
            }
        }
    }//GEN-LAST:event_requestTestJButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
          String username= jTextField1.getText();
       
        
        
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);
        
        for(AppointmentWorkRequest r: userAccount.getAppointmentWorkQueue().getAppointmentWorkRequestList())
        {
            String result = ((AppointmentBookingWorkRequest)r).getBookingResult();
            if(result!=null)
            {
             if(r.getSender().equals(userAccount))
            {
            if(r.getReceiver().getUsername().equals(username))
            {
                
                Object[] row = new Object[5];
                row[0] = r;
                row[2] = r.getDate();
                row[3] = r.getTime();
                if(result==null)
                 {
               row[4] = r.getStatus();
               row[1]="-";
                 }
                else
                {
               
                row[4] = result;
                row[1] = r.getReceiver();
                 }
            
            model.addRow(row);
            }
            }
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JButton requestTestJButton2;
    private javax.swing.JLabel usernamelbl;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
