/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Email.SwingEmailSender;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author varad
 */
public class DoctorMainJPanel extends javax.swing.JPanel {
public SwingEmailSender s;
    /**
     * Creates new form DoctorMainJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    
    public DoctorMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.doctorOrganization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecoSystem= ecoSystem;
        valueLabel.setText(enterprise.getName());   
        jLabel1.setText("Hello "+userAccount.getUsername());
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        performtestbtn = new javax.swing.JButton();
        addappointmentsbtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addappointmentsbtn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        performtestbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        performtestbtn.setText("Perform Lab Test");
        performtestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performtestbtnActionPerformed(evt);
            }
        });
        add(performtestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 261, 40));

        addappointmentsbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addappointmentsbtn.setText("Add Appointments");
        addappointmentsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addappointmentsbtnActionPerformed(evt);
            }
        });
        add(addappointmentsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 261, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 158, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 139, 33));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Send Prescription");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 261, 37));

        addappointmentsbtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addappointmentsbtn1.setText("View Schedule Appointments");
        addappointmentsbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addappointmentsbtn1ActionPerformed(evt);
            }
        });
        add(addappointmentsbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Send an Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 261, 44));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 650, 370));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Doctor Role");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Send physical reports");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 261, 44));
    }// </editor-fold>//GEN-END:initComponents

    private void addappointmentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addappointmentsbtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorAddAppointmentsJPanel", new DoctorAddAppointmentsJPanel(userProcessContainer, userAccount, doctorOrganization, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addappointmentsbtnActionPerformed

    private void performtestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performtestbtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorPeformLabTestJPanel", new DoctorPeformLabTestJPanel(userProcessContainer, userAccount, doctorOrganization, enterprise));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_performtestbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorSearchPatientsJPanel", new DoctorSearchPatients(userProcessContainer, userAccount, doctorOrganization, enterprise,ecoSystem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addappointmentsbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addappointmentsbtn1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorScheduleAppointmentsJPanel", new DoctorScheduleAppointmentsJPanel(userProcessContainer, userAccount, doctorOrganization, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addappointmentsbtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        s=new SwingEmailSender();
        s.SendEmail();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorScheduleAppointmentsJPanel", new DoctorSearchPatients2(userProcessContainer, userAccount, doctorOrganization, enterprise,ecoSystem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addappointmentsbtn;
    private javax.swing.JButton addappointmentsbtn1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton performtestbtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
